on:
  poll:
    url: https://macaumarksix.com/api/live2
    deduplicationKey: expect
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          openCode: ${{ on.poll.outputs.openCode }}
          zodiac: ${{ on.poll.outputs.zodiac }}
          openTime: ${{ on.poll.outputs.openTime }}
          wave: ${{ on.poll.outputs.wave }}         
        run: |
          echo "openCode: $openCode"
          echo "zodiac: $zodiac"
          echo "openTime: $openTime"
          echo "wave: $wave"
