on:
  poll:
    url: https://macaumarksix.com/api/live2
    deduplicationKey: expect
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest     
    steps:     
      - name: Send Bark Message
        run: |        
          key1="${{ on.poll.outputs.openCode }}"
          key2="${{ on.poll.outputs.zodiac }}"
          key3="${{ on.poll.outputs.openTime }}"
          key4="${{ on.poll.outputs.wave }}"
          # 拼接带回车换行的字符串，直接使用 URL 编码形式
          chinese_text="${key1}\r\n${key2}\r\n${key3}\r\n${key4}"

          # 使用 Python 进行 URL 编码（更稳定的编码方式）
          encoded_text=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$chinese_text'''))")        
                
          # 定义目标 URL 列表
          urls=("https://api.day.app/H9nYt9PJbr6LcBXYaiWPTU")
          # 循环发送请求到每个 URL
          for url in "${urls[@]}"
          do
            echo "输出结果"
            echo "Sending data to $url/$encoded_text"
            curl -s "$url/$encoded_text"
          done
